### ISSUE TITLE
libobjc2

### ISSUE THREAD

**Issue by wenq1** [mulle-objc/mulle-objc-runtime#14]
What's wrong with [libobjc2](https://github.com/gnustep/libobjc2) so that the mulle-objc-runtime is created instead?

**Comment by mulle-nat** [comment]
The question is too loaded to answer, because the mulle-objc-runtime is not created "instead of" libobjc2. mulle-objc-runtime and libobjc2 aren't even compatible. For more background on mulle-objc-runtime checkout [
mulle-objc: a new Objective-C
](https://www.mulle-kybernetik.com/weblog/2015/mulle_objc_a_new_objective_c_.html).

**Comment by wenq1** [comment]
I have read all that. Still out of curiosity on why won’t libobjc2 fits all needs of a runtime.

**Comment by mulle-nat** [comment]
The last time I looked more deeply at libobj2 has probably been 10 years ago or so, when I started writing the runtime. I am pretty sure, that [protocol classes ](https://www.mulle-kybernetik.com/weblog/2015/mulle_objc_inheriting_from_protocols.html) for example are still unique to mulle-objc-runtime.  
If I ask [perplexity.ai](https://www.perplexity.ai) I get

> libobjc2 is supports the Objective-C 2.0 ABI and provides support for blocks, properties, and ARC[[2]](https://apple-developer.org/resources/environments.html)
> It is the default runtime for the GNUstep Objective-C environment and is also used by some other projects.
>
>mulle-objc-runtime, on the other hand, is a runtime library that is part of the mulle-objc project, which is a complete implementation of the Objective-C language and runtime[[3]](https://github.com/mulle-objc)
> It provides a full-featured class system and supports some language features that are not supported by libobjc2, such as the ability to define instance variables in categories[[4]](https://mulle-objc.github.io/De-Re-mulle-objc/mydoc_differences.html)  However, it does not support some features of the Objective-C 2.0 ABI, such as non-fragile instance variables.

**Comment by wenq1** [comment]
ok
