### ISSUE TITLE
clang build - cannot "put up" an "issue"

### ISSUE THREAD

**Issue by wenq1** [mulle-objc/mulle-objc-runtime#16]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/110781/229274685-c66237b8-4db7-4bbe-b85f-287a79d2d7ea.png">
you will notice that there's no way to "put up an issue" as there is no such tab in a forked repo.

**Comment by wenq1** [comment]
<img width="908" alt="image" src="https://user-images.githubusercontent.com/110781/229274814-0b06e5ad-fb14-49b9-8a4b-e5bce09d0a31.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/110781/229274828-9698683f-2a06-4f0a-bef2-6da19c0c448e.png">

And unfortunately cmake-ninja is now 404.

**Comment by mulle-nat** [comment]
Putting the issues here is fine. I don't really know why or if I even disabled issues on the compiler, it may be a default setting when forking.

**Comment by mulle-nat** [comment]
So the problem with the description there, that it just staled and the script has been split into `cmake-ninja.{linux|darwin|windows}`. Got to fix the dox on that.

**Comment by wenq1** [comment]
No worries. It's already been built on M1.
