### ISSUE TITLE
@protocol @class, @protocolclass or whatever, doesn't work as explained in the doc.

### ISSUE THREAD

**Issue by wenq1** [mulle-objc/mulle-objc-runtime#17]
Implemented "multi inheritance" as per docs in the ref below. However it doesn't work as expect (from reading the doc). Maybe I'm doing it wrong?

Ref: https://www.mulle-kybernetik.com/weblog/2017/mulle_objc_multiple_inheritance.html

``` objc

@interface MulleBaseAnimal: NSObject {
}

- (NSString *) speak;

@end

@implementation MulleBaseAnimal

- (NSString *) speak
{
        return @"I love beer";
}

@end

@class MulleVersatilityProtocolClass;
@protocol MulleVersatilityProtocolClass
- (NSString *) perform;
@end

@implementation MulleVersatilityProtocolClass
- (NSString *) perform {
        return @"I can jump over the hoop";
}
@end




@interface MulleBelgiumDog: MulleBaseAnimal {}
- (NSString *) speak;
@end

@implementation MulleBelgiumDog

- (NSString *) speak
{
        return @"J'aime Leffe";
}

@end





@interface MulleGermanDog: MulleBaseAnimal<MulleVersatilityProtocolClass> {}
- (NSString *) speak;
@end

@implementation MulleGermanDog

- (NSString *) speak
{
        return @"Ich liebe Weissbier";
}

@end

int main (int argc, char *argv[])
{
        MulleBaseAnimal       * baseAnimal      = [[MulleBaseAnimal alloc] init];
        printf ("baseAnimal.1: %s\n", [[baseAnimal speak] UTF8String]);

        MulleBelgiumDog       * belgiumDog      = [[MulleBelgiumDog alloc] init];
        printf ("belgiumDog.1: %s\n", [[belgiumDog speak] UTF8String]);

        MulleGermanDog        * germanDog       = [[MulleGermanDog alloc] init];
        printf ("germanDog.1: %s\n", [[germanDog speak] UTF8String]);

        printf ("germanDog.2: %s\n", [[germanDog perform] UTF8String]);

        return 0;
};
```

Building & running:
```
$ make; ./mulle-testproto
[ 50%] Built target _1_mulle-testproto
[100%] Linking C executable mulle-testproto
[100%] Built target mulle-testproto
baseAnimal.1: I love beer
belgiumDog.1: J'aime Leffe
germanDog.1: Ich liebe Weissbier
mulle_objc_universe 0x1043d9488 fatal: unknown method ae293c20 "-perform" in class 109d90ee "MulleGermanDog"
zsh: abort      ./mulle-testproto
```

I took the liberty to make a minimum reproduction repo from a clone of mulle-markdow. Note the branch "versatile".
https://github.com/wenq1/mulle-markdown/tree/versatile

**Comment by wenq1** [comment]
And nowhere in the document says [NSString cStringWithEncoding:] does not exist. Well.... A bit more doc might help.......

**Comment by mulle-nat** [comment]
The most relevant documentation for protocol classes is probably [De Re mulle-objc](https://mulle-objc.github.io/De-Re-mulle-objc/mydoc_protocolclass.html).  The "background" info on mulle-kybernetik is probably not technically wrong, but there is no proper compiler language support for protocol classes yet, for ... reasons...

Actual working code of a protocol class can be found through the Foundation, but here is
a simple one: [MulleObjCOutputStream.h](hhttps://github.com/MulleFoundation/MulleObjCPlistFoundation/blob/release/src/Stream/MulleObjCStream.h#L54) and  [MulleObjCOutputStream.m](https://github.com/MulleFoundation/MulleObjCPlistFoundation/blob/release/src/Stream/MulleObjCStream.m#L47).

You can probably figure it out from there.

**Comment by mulle-nat** [comment]
I think there is a reason why `-cStringWithEncoding:` does not exist. The reason is (probably) something like this. The default `char *` representation in mulle-objc is **UTF8**. The `cString` methods are used for the default system encoding, whatever that may be. So `-cStringWithEncoding:` doesn't really make sense in mulle-objc. It's possibly explained somewhere in some header.

**Comment by wenq1** [comment]
works now
