### ISSUE TITLE
_resignAsRootObject is never used in practice

### ISSUE THREAD

**Issue by mulle-nat** [mulle-objc/mulle-objc-runtime#4]
This means (to me):

* could remove rootobjects and use an autoreleasepool wired to the universe. this is not the same pool as the default NSThread autoreleasepool
* remove _resignAsRootObject
* use pushToRootPool to make root objects stick.

**Comment by mulle-nat** [comment]
That is not actually true. It is used in the class variable feature, that isn't currently used.
Idea: throw away the class variable feature. Use `static` variables like all code does.
Questions: why are class variable even root objects, when they are attached to classes which are by themselves root objects of some sort.

Then also NSThread can get into a detached state, which means it is not tracked as a NSThread object anymore. But the object still exists and was made a rootObject and at the end is converted into a non rootobject.

Remedies: mark NSThread objects as detached and not make them rootObjects.

**Comment by codeon-nat** [comment]
Keep roots "as is" for now, but try to avoid using them.
